### PR TITLE
Switch from go-yaml to candiedyaml

### PR DESCRIPTION
**Pull request by karlkfi**
- Better parse error messages
- Apache v2 instead of LGPL (for safe source vendoring)

### CODE REVIEW

**Comment by karlkfi** [comment]
The shippable failure is because the test expects ordering to be consistent (or alphabetical), which isn't guaranteed.  I think the test is wrong, but I don't know if go-test actually guaranteed order/alphabetization.

**Comment by ghodss** [comment]
@karlkfi Now that cloudfoundry-incubator/candiedyaml#14 is fixed this should be mergable. Can you re-push the commit to rekick Shippable?

**Comment by karlkfi** [comment]
@ghodss done, looks happy now.

**Comment by tony** [comment]
Any update on this @ghodss ?

**Comment by ghodss** [comment]
Merged! Thanks @karlkfi :)

**Pull request merged**
