### PR TITLE
Add support to avoid converting numbers to float64.

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by smarterclayton** [comment]
Looks ok to me at first pass

**Comment by vishh** [comment]
Ping @ghodss

**Comment by ghodss** [comment]
Hi! Sorry for the delay on reviewing this.

My question is, is there a situation where this ISN'T what we want? It seems that rendering the number as a string is always a good idea, and it seems as though if the number does happen to be a float, that the json library will prepare a string that looks like a float as well. If so, can we just change the Marshal function to always run d.UseNumber()?

(See http://stackoverflow.com/questions/22343083/json-marshaling-with-long-numbers-in-golang-gives-floating-point-number for reference, which includes a link to https://play.golang.org/p/TRo0v4yeBO which seems to render floats and ints both correctly with UseNumber() on.)

**Comment by vishh** [comment]
+1. I was wondering if changing the existing API might break some users.

**Comment by ghodss** [comment]
Actually, I think the premise of this issue is incorrect. This patch makes it so all numbers render into YAML as strings, which is not right. If you go back to the issue that prompted this, GoogleCloudPlatform/kubernetes#4041, you can see there that the issue was not due to a number incorrectly rendering as a float, but instead as a 64-bit number being rendered as a 32-bit one, causing a float output. I'm going to close this but feel free to respond if I'm missing something.

**Comment by vishh** [comment]
There are two issues here. One is that of YAML lib converting numbers to
float64. The other is kubernetes incorrectly handling int64 value as int in
its v1beta1 API. Both of them have to be addressed. If I define a go struct
which has an int64 field, and marshal it into YAML, I should be able to
Unmarshal it again as an int64.

**Comment by vishh** [comment]
@ghodss: This PR is important for Kubernetes. I would appreciate if we can resolve this issue quickly. Thanks!

**Comment by vishh** [comment]
Have a look at this sample code [here](https://gist.github.com/vishh/046c4f226fcf65fb1d5e). An `int64` when marshaled into Yaml becomes a `float64`.

**Comment by ghodss** [comment]
@vishh You are right. https://github.com/ghodss/yaml/commit/588cb435e59ee8b6c2795482887755841ad67207 should be the actual fix to make sure numbers do not get arbitrarily converted to float64.

**Comment by vishh** [comment]
Thanks for the quick fix @ghodss. I will pull in your changes into
kubernetes soon.

**Pull request closed without merging**
