### PR TITLE
Return typed errors from exported funcs

### PR DESCRIPTION
**Pull request by juanvallejo**
By adding a YAMLError type and returning typed errors from exported
functions, downstream users will be able to easily distinguish
yaml-specific errors.

Related downstream PR: https://github.com/kubernetes/kubernetes/pull/38905

cc @deads2k @fabianofranz

### CODE REVIEW

**Comment by fabianofranz** [comment]
cc @ghodss

**Comment by ghodss** [comment]
Hi! First of all, thanks for working on enhancing the error messaging in kube, very excited for that.

I'd just like to understand this a little better... in #38905, you write:

> No, upon looking at the function that is eventually called in the ghodss/yaml package from the Decode method implemented in our pkg/util/yaml/decoder.go, errors prefixed with yaml: ... only occur when a call to gopkg.in/yaml.v2#Unmarshal results in an error. The only case that returns an error without the yaml: prefix is if ghodss/yaml/yaml.go#convertToJSONableObject fails, which will only happen if an unknown key type is given

But isn't [this one](https://github.com/juanvallejo/yaml/blob/80e022e4747c47b2dc505b7324c39ca8ae151c9e/yaml.go#L26) an error that comes from the JSON library, not the YAML? What exactly are you trying to distinguish here?

And, if that also is considered a YAML error, then I would imagine that the [Unsupported map key](https://github.com/juanvallejo/yaml/blob/80e022e4747c47b2dc505b7324c39ca8ae151c9e/yaml.go#L180) error would also qualify as a YAML error, since it's a case where a key of your map is just simply not going to be valid in the golang-struct world. Do you really need to differentiate against this one case?

**Comment by juanvallejo** [comment]
@ghodss 
> But isn't this one an error that comes from the JSON library, not the YAML? What exactly are you trying to distinguish here?

Thanks for the feedback, I will update the PR to not type the errors there. 

> And, if that also is considered a YAML error, then I would imagine that the Unsupported map key error would also qualify as a YAML error, since it's a case where a key of your map is just simply not going to be valid in the golang-struct world. Do you really need to differentiate against this one case?

Although I would not consider the above a YAML error (will amend PR), I do think that the Unsupported map key error would count as one; it is not using the `encoding/json` library to marshal the input, and it is being entirely parsed within this yaml package. If you feel this error should not be typed though, I can definitely update this PR accordingly.

The reason behind having this package return typed errors, is so that they can be distinguished from `json.SyntaxError` types downstream.

Thanks again for the feedback.

**Comment by ghodss** [comment]
Okay so I've been looking at this more closely and I don't think this library is where you want to type this error. After all, if you look at the Unmarshal function with your changes [here](https://github.com/juanvallejo/yaml/blob/2f71cb8683d8cc615ed050e3f71e0950d13fc230/yaml.go#L38), it returns a YAMLError 100% of the time, which implies that you could actually type this one step higher in the call stack and that there's no value to doing the typing here. The non-YAMLError case that we discussed in Marshal [here](https://github.com/juanvallejo/yaml/blob/2f71cb8683d8cc615ed050e3f71e0950d13fc230/yaml.go#L21) is really just an edge case that your object marshals poorly, which is quite rare, and not useful to your downstream PR, AFAICT, since that one is mostly about decoding/unmarshaling.

Looking at the Kubernetes code, I think the right place to type this is [here](https://github.com/juanvallejo/kubernetes/blob/5dd2984322e07e2c9a4125140c2b711a2fed2f65/staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go#L72) where the YAML-specific decode logic is actually called. At that point you know you're specifically calling YAML to decode so you can return a YAML-specific error. Now, I do wonder why that function is using `yaml.YAMLToJSON(bytes)` and THEN `json.Unmarshal(data, into)`, since `yaml.Unmarshal(data, into)` would actually handle that case fine, so that should probably be improved as well, unless I'm missing something.

Let me know what you think.

**Comment by juanvallejo** [comment]
@ghodss Thank you for all of your feedback! 
> Looking at the Kubernetes code, I think the right place to type this is here where the YAML-specific decode logic is actually called. At that point you know you're specifically calling YAML to decode so you can return a YAML-specific error

I agree, taking into account this and the previous statement, it does make more sense to type the error higher up in the call stack.

> Now, I do wonder why that function is using yaml.YAMLToJSON(bytes) and THEN json.Unmarshal(data, into), since yaml.Unmarshal(data, into) would actually handle that case fine, so that should probably be improved as well

Definitely, I will update my [kubernetes PR](https://github.com/juanvallejo/kubernetes/blob/5dd2984322e07e2c9a4125140c2b711a2fed2f65/staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go#L72) to instead call `yaml.Unmarshal` [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/yaml/decoder.go#L76) and type the error there as well.

Thanks again

**Comment by juanvallejo** [comment]
Closing in favor of fix suggested in https://github.com/ghodss/yaml/pull/18#issuecomment-274933932. Patched [downstream](https://github.com/kubernetes/kubernetes/pull/38905) instead.

**Pull request closed without merging**
