### PR TITLE
Add UnmarshalStrict for strict yaml unmarshaling

### PR DESCRIPTION
**Pull request by tanner-bruce**

### CODE REVIEW

**Comment by dims** [comment]
@ghodss @tanner-bruce +1 from me. we need this for the kubernetes/kubernetes repo linked issue.

**Comment by ghodss** [comment]
Thank you for the PR!

We have already merged #33, which resolves this issue.

**Comment by dims** [comment]
@ghodss #33 is not enough unfortunately AFAICT. in k/k we need the `yaml.UnmarshalStrict(bytes, into)` signature. please see:

https://github.com/kubernetes/kubernetes/pull/67594#issuecomment-414466664

**Comment by tanner-bruce** [comment]
@ghodss, as @dims said, this is different than #33. This implements `yaml.UnmarshalStrict`, which has a use case different from YAMLToJSONStrict.

**Pull request closed without merging**
