### PR TITLE
Updating go.mod to take the latest release of go-yaml

### PR DESCRIPTION
**Pull request by njuettner**
Updating go-yaml to prevent abuse of high CPU/ memory consumption:
https://github.com/go-yaml/yaml/releases/tag/v2.2.4

Issue where it was mentioned:
https://github.com/kubernetes/kubernetes/issues/83253

### CODE REVIEW

**Comment by petrkotas** [comment]
Awesome, I was about to submit the same patch! Thanks @njuettner.

**Comment by petrkotas** [comment]
Hi @njuettner I have a proposal, would you please change the commit "Update go to version 1.13 " to add go 1.13 instead of replacing it? I believe this will make this simper to review.

Hi @ghodss would you mind please, taking a look at this PR? I believe it is relevant to the community using this great library. Thank you.

**Comment by njuettner** [comment]
You mean only adding go 1.13 in travis.yaml? If so this will break CI again. 

It fails to build due because of the last line in go.mod which is automatically added when updating the dependencies (I'm using go 1.13 right now so it was added automatically).

I can try to use go 1.12 and also add it into Ttravis.

**Comment by petrkotas** [comment]
I know, when I did PRs to other repos I manually deleted the go 1.13 line from all repos. This enabled the compilation on other go compilers.

I know it is a dumb, sorry for that.

**Comment by petrkotas** [comment]
Hi @ghodss, sorry for bothering you. Would you mind taking a look at this PR?

**Pull request closed without merging**
